### PR TITLE
Added the print functionality

### LINKED ISSUE #1: [PROPOSAL] Print functionality
First, nice project !
I may find some times to develop the "print" functionality for the document. Do you accept usage of external library or you want to keep all 'made by hand' ? 
Anyway, if you're still up to that, I'll create a new branch and work on that !

### PR DESCRIPTION
**Pull request by SelenaZelia**
This closes #1
Using the "print" button now launch a print frame, which got enough
options in my opinion.
For now it print at the top (as a title) the document name & software
name, and the page number at the bottom. I'll change that later on to
give the user a way of editing it

Also kinda not used to branch thingy with Github, so it updated the main branch... Anyway that should not be a problem since the program compile !

Finally, I only got a pdf printer, so couldn't try on a physical one, if someone could print a test page that would be neat !
printfct

---

Important : you'd need to recompile and recommit/push for change to affect the .jar, I only edited the sources !

### CODE REVIEW

**Comment by frank184** [comment]
Hey, I'm finishing up work, but I promise to review this over the weekend!

It actually looks pretty sick, awesome man!

**Comment by SelenaZelia** [comment]
Hope it will be good enough then ! :D

**Comment by frank184** [comment]
This is perfect! I'll add this to page setup, then maybe figure out a way to start the print function on that page.

**Comment by SelenaZelia** [comment]
Ah ah alright nice ! :)

**Pull request merged**
